scrape_configs:
  - job_name: 'traefik'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['traefik:8082']

  # - job_name: cadvisor
  #   scrape_interval: 5s
  #   static_configs:
  #   - targets: ['cadvisor:8080']
