{
 "title": "OctoPrint",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Extruder Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_temperature",
     "select": [
      [
       { "params": [ "tool0_actual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_temperature",
     "query": "SELECT mean(\"tool0_target\") FROM \"mk3s_temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "tool0_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Live Feed",
   "type": "text",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<iframe width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"http://192.168.1.82/webcam/?action=stream\"></iframe>"
   },
   "content": "<iframe width=\"650\" height=\"100%\" frameborder=\"0\" scrolling=\"yes\" marginheight=\"0\" marginwidth=\"0\" src=\"http://192.168.1.82/webcam/?action=stream\"></iframe>"
  },
  {
   "title": "Bed Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Current",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_temperature",
     "select": [
      [
       { "params": [ "bed_actual" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Target",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_temperature",
     "query": "SELECT mean(\"tool0_target\") FROM \"mk3s_temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "bed_target" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power Usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "switch.printer",
     "select": [
      [
       { "params": [ "current_power_w" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Completion",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mk3s_progress",
     "select": [
      [
       { "params": [ "completion" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Print Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_progress",
     "select": [
      [
       { "params": [ "print_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Print Time Left",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "mk3s_progress",
     "select": [
      [
       { "params": [ "print_time_left" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}